name = "getting-started-rust-cloudflare-workers"
main = "build/worker/shim.mjs"
compatibility_date = "2022-04-19"

[vars]
WORKERS_RS_VERSION = "0.0.16"

[build]
command = "cargo install -q worker-build --version 0.0.9 && worker-build --release"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
